In [1]:
import pandas as pd
df = pd.read_csv(r'/Users/suhaas/Machine-Learning/manu-sus-engine/Merged_dataset.csv')
df.head()

,Batch_ID,Duration_Minutes,Data_Points,Avg_Temperature,Max_Temperature,Avg_Pressure,Max_Compression_Force,Avg_Power_Consumption,Max_Motor_Speed,Avg_Humidity_Percent,...,Compression_Force,Machine_Speed,Lubricant_Conc,Moisture_Content,Tablet_Weight,Hardness,Friability,Disintegration_Time,Dissolution_Rate,Content_Uniformity
0,T001,210,211,35.222405,64.464826,0.989573,14.219469,21.821216,875.033250,38.260003,...,12.5,150,1.0,2.1,199.8,95,0.65,8.2,89.3,98.7
1,T002,242,243,34.118974,68.199612,0.990320,18.252780,21.761982,870.711447,37.468800,...,15.0,120,0.8,2.8,201.3,110,0.45,12.1,87.9,101.2
2,T003,257,258,35.232192,65.789715,0.973079,12.139067,23.328404,876.255527,36.915295,...,10.8,180,1.2,1.9,198.5,85,0.78,6.8,91.5,97.3
3,T004,231,232,37.009830,68.036694,0.969539,10.457428,21.305877,854.039596,37.631641,...,8.5,200,1.5,1.5,203.2,72,0.95,5.5,93.8,95.9
4,T005,246,247,33.918228,74.712142,0.969525,18.036629,24.982074,906.424204,36.420933,...,16.2,100,0.6,3.2,202.7,125,0.38,14.8,85.1,103.5

In [3]:
df["Energy_Consumption_kWh"] = df["Avg_Power_Consumption"] * (df["Duration_Minutes"] / 60)
df.head()

,Batch_ID,Duration_Minutes,Data_Points,Avg_Temperature,Max_Temperature,Avg_Pressure,Max_Compression_Force,Avg_Power_Consumption,Max_Motor_Speed,Avg_Humidity_Percent,...,Machine_Speed,Lubricant_Conc,Moisture_Content,Tablet_Weight,Hardness,Friability,Disintegration_Time,Dissolution_Rate,Content_Uniformity,Energy_Consumption_kWh
0,T001,210,211,35.222405,64.464826,0.989573,14.219469,21.821216,875.033250,38.260003,...,150,1.0,2.1,199.8,95,0.65,8.2,89.3,98.7,76.374255
1,T002,242,243,34.118974,68.199612,0.990320,18.252780,21.761982,870.711447,37.468800,...,120,0.8,2.8,201.3,110,0.45,12.1,87.9,101.2,87.773329
2,T003,257,258,35.232192,65.789715,0.973079,12.139067,23.328404,876.255527,36.915295,...,180,1.2,1.9,198.5,85,0.78,6.8,91.5,97.3,99.923333
3,T004,231,232,37.009830,68.036694,0.969539,10.457428,21.305877,854.039596,37.631641,...,200,1.5,1.5,203.2,72,0.95,5.5,93.8,95.9,82.027627
4,T005,246,247,33.918228,74.712142,0.969525,18.036629,24.982074,906.424204,36.420933,...,100,0.6,3.2,202.7,125,0.38,14.8,85.1,103.5,102.426504

In [4]:
#0.82 kg CO2 per kWh  (India average)
df["Carbon_Emissions_kgCO2"] = df["Energy_Consumption_kWh"] * 0.82
df.head()

,Batch_ID,Duration_Minutes,Data_Points,Avg_Temperature,Max_Temperature,Avg_Pressure,Max_Compression_Force,Avg_Power_Consumption,Max_Motor_Speed,Avg_Humidity_Percent,...,Lubricant_Conc,Moisture_Content,Tablet_Weight,Hardness,Friability,Disintegration_Time,Dissolution_Rate,Content_Uniformity,Energy_Consumption_kWh,Carbon_Emissions_kgCO2
0,T001,210,211,35.222405,64.464826,0.989573,14.219469,21.821216,875.033250,38.260003,...,1.0,2.1,199.8,95,0.65,8.2,89.3,98.7,76.374255,62.626889
1,T002,242,243,34.118974,68.199612,0.990320,18.252780,21.761982,870.711447,37.468800,...,0.8,2.8,201.3,110,0.45,12.1,87.9,101.2,87.773329,71.974129
2,T003,257,258,35.232192,65.789715,0.973079,12.139067,23.328404,876.255527,36.915295,...,1.2,1.9,198.5,85,0.78,6.8,91.5,97.3,99.923333,81.937133
3,T004,231,232,37.009830,68.036694,0.969539,10.457428,21.305877,854.039596,37.631641,...,1.5,1.5,203.2,72,0.95,5.5,93.8,95.9,82.027627,67.262654
4,T005,246,247,33.918228,74.712142,0.969525,18.036629,24.982074,906.424204,36.420933,...,0.6,3.2,202.7,125,0.38,14.8,85.1,103.5,102.426504,83.989733

In [6]:
targets = [
    "Hardness",
    "Friability",
    "Disintegration_Time",
    "Dissolution_Rate",
    "Content_Uniformity",
    "Energy_Consumption_kWh",
    "Carbon_Emissions_kgCO2"
]

X = df.drop(columns=targets + ["Batch_ID"])
y = df[targets]

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Duration_Minutes          60 non-null     int64
 1   Data_Points               60 non-null     int64
 2   Avg_Temperature           60 non-null     float64
 3   Max_Temperature           60 non-null     float64
 4   Avg_Pressure              60 non-null     float64
 5   Max_Compression_Force     60 non-null     float64
 6   Avg_Power_Consumption     60 non-null     float64
 7   Max_Motor_Speed           60 non-null     float64
 8   Avg_Humidity_Percent      60 non-null     float64
 9   Avg_Flow_Rate_LPM         60 non-null     float64
 10  Avg_Vibration_mm_s        60 non-null     float64
 11  Max_Vibration_mm_s        60 non-null     float64
 12  Max_Humidity_Percent      60 non-null     float64
 13  Max_Flow_Rate_LPM         60 non-null     float64
 14  Avg_Motor_Speed_RPM       60 non-null     float64
 15  Avg_Compression_Force_kN  60 non-null     float64
 16  Max_Power_Consumption_kW  60 non-null     float64
 17  Max_Pressure_Bar          60 non-null     float64
 18  Granulation_Time          60 non-null     int64
 19  Binder_Amount             60 non-null     float64
 20  Drying_Temp               60 non-null     int64
 21  Drying_Time               60 non-null     int64
 22  Compression_Force         60 non-null     float64
 23  Machine_Speed             60 non-null     int64
 24  Lubricant_Conc            60 non-null     float64
 25  Moisture_Content          60 non-null     float64
 26  Tablet_Weight             60 non-null     float64
dtypes: float64(21), int64(6)
memory usage: 12.8 KB

In [11]:
numeric_cols = X.select_dtypes(include=["int64","float64"]).columns
categorical_cols = X.select_dtypes(include=["object","category"]).columns

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numeric_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
])

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [14]:
rf_pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", MultiOutputRegressor(
        RandomForestRegressor(
            n_estimators=400,
            max_depth=None,
            random_state=42,
            n_jobs=-1
        )
    ))
])

In [16]:
%pip install xgboost
from xgboost import XGBRegressor

Requirement already satisfied: xgboost in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: numpy in /Users/suhaas/Library/Python/3.14/lib/python/site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from xgboost) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
xgb_pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", MultiOutputRegressor(
        XGBRegressor(
            n_estimators=400,
            max_depth=6,
            learning_rate=0.1,
            random_state=42,
            n_jobs=-1
        )
    ))
])

In [21]:
from sklearn.model_selection import cross_val_score, KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

rf_scores = cross_val_score(rf_pipeline, X, y, cv=kf, scoring="r2")
xgb_scores = cross_val_score(xgb_pipeline, X, y, cv=kf, scoring="r2")

In [32]:
rf_scores

array([0.90434714, 0.84529182, 0.93022771, 0.95490356, 0.96093552])

In [33]:
rf_scores.mean()

np.float64(0.9191411501074527)

In [34]:
xgb_scores

array([0.85161966, 0.86027032, 0.93033296, 0.94262969, 0.94993013])

In [35]:
xgb_scores.mean()

np.float64(0.9069565534591675)

In [36]:
#we are going forward with random forest model